apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-04-29T19:34:45Z"
  labels:
    app: argocd-server-node-port
  name: argocd-server-node-port
  namespace: argocd
  resourceVersion: "5245"
  uid: 7c0aa16e-ad0a-4bd6-867f-b95ed0750410
spec:
  clusterIP: 10.100.62.26
  clusterIPs:
  - 10.100.62.26
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
